language: php

php:
  - 7.4

before_script:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover ./clover.xml
after_script:
  - vendor/bin/php-coveralls -x ./clover.xml -o ./coveralls.json -v